### ISSUE TITLE
Использовать селекторы только по классам

### ISSUE THREAD

**Issue by Burize** [prodderman/resume#11]
![2018-02-22 10 59 37](https://user-images.githubusercontent.com/22253666/36520990-ed2b4f84-17c6-11e8-939e-9385216b9b39.png)
--------
![2018-02-22 10 48 52](https://user-images.githubusercontent.com/22253666/36521001-f4de3df4-17c6-11e8-8abc-a55e4b0817ab.png)

**Comment by Geksanit** [comment]
можешь закрывать этот issue
