### ISSUE TITLE
Невалидный CSS

### ISSUE THREAD

**Issue by Burize** [prodderman/resume#12]
![2018-02-22 11 02 36](https://user-images.githubusercontent.com/22253666/36521020-13cf46ae-17c7-11e8-92b4-8affd971787b.png)
---------
![2018-02-22 10 58 07](https://user-images.githubusercontent.com/22253666/36521025-1a4fb0fe-17c7-11e8-8194-c5a6b628e4f8.png)

**Comment by Geksanit** [comment]
line-height @font-size - 10 
в результате получается отрицательное значение - тоже невалидно

**Comment by Geksanit** [comment]
Лучше совсем без вычитания, если `@font-size` изменится, нужно будет опять проверять все вычитания. Для задания шрифта относительно родителя есть единица измерения em.

**Comment by Geksanit** [comment]
Закрывай ишью.
