### ISSUE TITLE
Элементы не по БЭМу

### ISSUE THREAD

**Issue by Geksanit** [prodderman/resume#14]
`.resume__personal` и другие подобные элементы находятся вне своего блока `.resume`, которого даже нет.

**Comment by Geksanit** [comment]
Почему бы не выделить логические блоки контакты/скиллы/...  ?

**Comment by prodderman** [comment]
`.resume` это класс страницы и используется как блок

**Comment by Geksanit** [comment]
почему тогда родитель `.resume__personal` не `.resume` или его элемент ?

**Comment by Geksanit** [comment]
`.resume` я так и не нашел, нет такого html элемента с таким классом.

**Comment by chmnkh** [comment]
Блок round, опциональная пикча - тоже не по БЭМу сделана.

**Comment by chmnkh** [comment]
Закрывай ишью.
