### ISSUE TITLE
section не по БЭМ

### ISSUE THREAD

**Issue by anarkiVan** [prodderman/resume#2]
`section--${title}` я так понимаю это у тебя это модификатор?
Пройдись по всему проекту, в skill тоже заметил.

**Comment by anarkiVan** [comment]
Еще замечание, нельзя перетирать стили блока другим. Компоненты все должны быть инкапсулированы и самодостаточны
`&--profile .icon-inner
    background-image: url(./img/profile.png)`

**Comment by prodderman** [comment]
по второму комменту исправил, а вот по первому не понял, объясните по подробней

**Comment by anarkiVan** [comment]
section--skills, section--software это имена будто других блоков, но они определенны в стилях блока section. У блока по БЭМ есть элементы и модификаторы, для которых есть свои правила именования)

**Comment by prodderman** [comment]
как  понял ошибка в том, что нужно использовать одиночный дефис?

**Comment by anarkiVan** [comment]
меня запутала немного такая конструкция. 

```
&-contact
    .contact
      margin-bottom: 1.4rem
```
Сейчас идет изменения в стилях другого блока блоком section, так делать нельзя. Если мы хотим спозиционировать другой блок есть два решения:
1. Использовать миксин. Так делать не рекомендуется и не стоит. Т.к. нет гарантии, что точно стили миксина применятся.
2. Использовать блок обертку, который будет внутри себя содержть блок БЭМ и ему задавать уже все отступы.
Надеюсь все понятно объяснил)

**Comment by prodderman** [comment]
исправил

**Comment by Geksanit** [comment]
Закрывай
