### ISSUE TITLE
Линия в заголовках не по центру

### ISSUE THREAD

**Issue by anarkiVan** [prodderman/resume#3]
![image](https://user-images.githubusercontent.com/16408935/35438535-7eb7b450-02c9-11e8-9238-b957a59d524d.png)

**Comment by prodderman** [comment]
![image](https://user-images.githubusercontent.com/24736776/35494336-8ff9c90e-04ec-11e8-8482-1b355e66334a.png)
у вас есть пункт по поводу этого, но все равно исправил

**Comment by anarkiVan** [comment]
Тут и имеется ввиду, что у дизайнера может криво лежать линия в макете и тебе не надо хардкодить подстраиваться под эту халатность)
