### ISSUE TITLE
Внешняя геометрия блока

### ISSUE THREAD

**Issue by kinda-neat** [prodderman/resume#5]
Сразу скажу по ишьюсам, по большей части ревьюверы оставляют ишьюсы и сами закрывают их, так что как сделаешь пиши в комментариях к ишьюсу что сделал и пиши вопросы, которые возникают при выполнении если нужно. И еще, когда оставляют ишьюс, пройдись по всем своим проектам и посмотри а нет ли там такого же косяка, так сэкономишь и свое время и наше)
А теперь к делу, блок не должен влиять на свое окружение, т. е. блоку не следует задавать внешнюю геометрию (в виде отступов, границ, влияющих на размеры) и позиционирование. Теряется независимость, при которой возможно повторное использование или перенос блоков с места на место.
У тебя же
![2018-01-28 12-42-01](https://user-images.githubusercontent.com/27883524/35479398-1a9fc0c8-0429-11e8-985b-10fde89712db.png)
Это нужно везде поправить :)

**Comment by prodderman** [comment]
Готово

**Comment by kinda-neat** [comment]
Когда коммитишь помечай # номера ишьюсов, которых касается коммит (пример: #5, #25 ), так будет гораздо удобнее ревьювить :)

**Comment by kinda-neat** [comment]
Миксы использовать плохо, в стандартах есть ясное объяснение почему, везде это нужно исправить

**Comment by Geksanit** [comment]
Закрывай ишью
