### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by kinda-neat** [prodderman/resume#6]
Объясни что это за сущности по БЭМ?
![2018-01-31 13-25-27](https://user-images.githubusercontent.com/27883524/35608207-9fb1aa0c-068a-11e8-879e-b6799f01028f.png)

**Comment by prodderman** [comment]
Это модификаторы, кроме resume

**Comment by kinda-neat** [comment]
Есть несколько нотаций каким образом обозначать модификаторы, мы используем вот такие
https://ru.bem.info/methodology/quick-start/#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80
Имя модификатора отделяется от имени блока или элемента одним подчеркиванием (_).

**Comment by prodderman** [comment]
хорошо, а на счет класса resume, я могу так делать, если мне понадобится переопределить стили для конкретной страницы? Или лучше через модификатор?

**Comment by kinda-neat** [comment]
Страницу тоже представляет блок: .main-page, .login и т.д.
Какие именно стили страницы ты собираешься переопределять?

**Comment by Geksanit** [comment]
непонятно какой коммит тут исправляет, но стало лучше, можешь закрывать
