### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by kinda-neat** [prodderman/resume#8]
Подключить в каждом проекте 
В стандартах есть про это пункт, HTML -> Подключаемые файлы

**Comment by prodderman** [comment]
готово

**Comment by kinda-neat** [comment]
Плиз когда коммитишь помечай номер ишьюса: git commit -m "favicon #8"

**Comment by kinda-neat** [comment]
И не все так просто, там еще для safari, открывал стандарты?

**Comment by prodderman** [comment]
это можно сделать через webpack, или нужно вручную?

**Comment by kinda-neat** [comment]
В риззоме я оставлял ссылку на то как это можно сделать через webpack)
