### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Burize** [prodderman/resume#9]
Есть 2 замечания:

в командах (`"command": "webpack",`) всегда указываются локальные модули, а не установленные глобально (как сейчас указан webpack). Может показаться не существенно, но это избавляет от конфликтов при сборке, потому что у меня (ну или другого разработчика) может быть глобально установлена версия отличная от той, которая использовалась при разработке.

devDependencies - это зависимости используемые при разработке: линтеры, dev-sever, может какие-либо типы и тд. Все остальное это обычные dependencies, которые используются при сборки продакшена.

**Comment by Geksanit** [comment]
закрывай этот ишью
